CREATE TABLE JobTable (
    JobID INT PRIMARY KEY AUTO_INCREMENT,
    Position VARCHAR(255),
    Company VARCHAR(255),
    JobLocation VARCHAR(255),
    Status VARCHAR(50),
    JobType VARCHAR(50)
);
INSERT INTO JobTable (Position, Company, JobLocation, Status, JobType)
VALUES ('Civil Engineer','Bechtelar-Bednar','Kiamba','declined','internship'),
VALUES ('Accounting Assistant III','Kunze and Sons','Kafr Mandā','interview','remote'),
VALUES ('Environmental Tech','Cremin LLC','Meixian','declined','full-time'),
VALUES ('Actuary','Klocko and Sons','Dianfang','pending','full-time'),
VALUES ('Account Executive','Mraz-Hilpert','Kota Kinabalu','pending','full-time'),
VALUES ('Dental Hygienist','Little LLC','Rebrikha','declined','remote'),
VALUES ('Graphic Designer','Barrows Inc','Baihua','interview','internship'),
VALUES ('Pharmacist','Schimmel, Beahan and Baumbach','Jakhaly','interview','internship'),
VALUES ('Assistant Professor','Stehr, Homenick and Turcotte','Shizi','interview','full-time'),
VALUES ('Desktop Support Technician','Fritsch-Muller','Kosai-shi','declined','remote'),
VALUES ('Nuclear Power Engineer','Marvin-Wisoky','Sulkava','interview','part-time'),
VALUES ('Staff Scientist','Schmitt, Murphy and Simonis','Puntaru','declined','internship'),
VALUES ('Senior Editor','Hills, Ward and Gleichner','Giồng Riềng','pending','part-time'),
VALUES ('Executive Secretary','Macejkovic Group','Piracuruca','interview','full-time'),
VALUES ('Accounting Assistant III','Littel, Cummerata and Wisoky','Simitli','pending','remote'),
VALUES ('Chemical Engineer','Rutherford-Considine','Sukosari','declined','remote'),
VALUES ('Associate Professor','Runolfsdottir and Sons','Hewan','interview',full-time'),
VALUES ('Clinical Specialist','Hahn-Koss','Tiancheng','pending','part-time'),
VALUES ('Automation Specialist II','Wilkinson-Kub','Kuznetsovs’k','declined','remote'),
VALUES ('Clinical Specialist','Klein, Wunsch and Gutmann','Neiguan','interview','full-time'),
VALUES ('Developer III','Shanahan-Runte','Liuhe','pending','remote'),
VALUES ('Librarian','Crooks-Dare','Lévis','interview','internship'),
VALUES ('Chief Design Engineer','Bednar-Osinski','Langley','pending','part-time'),
VALUES ('Help Desk Operator','Gislason, Rice and Rosenbaum','As Suwaydā','pending','part-time'),
VALUES ('Systems Administrator II','Grimes, Cormier and Funk','Levashi','interview','full-time'),
VALUES ('Database Administrator II','Bode, Bernier and Trantow','San Agustin','pending','full-time'),
VALUES ('Programmer Analyst I','Smitham Inc','Shanghu','declined','internship'),
VALUES ('Assistant Professor','Roob and Sons','Kebonsari Kidul','declined','full-time'),
VALUES ('Geologist IV','Kreiger, Thiel and McDermott','Cerenti','declined','remote'),
VALUES ('Legal Assistant','Wiza, Sawayn and Hayes','Rio Pardo','declined','part-time'),
VALUES ('Internal Auditor','Boehm, Bashirian and Ledner','Princeton','interview','part-time'),
VALUES ('Assistant Media Planner','West-Cruickshank','San Ramón de la Nueva Orán','pending','full-time'),
VALUES ('Quality Control Specialist','Bode Group','Kosaya Gora','declined','full-time'),
VALUES ('Senior Financial Analyst','Predovic and Sons','Estoi','pending','part-time'),
VALUES ('Help Desk Operator','Waters-Koch','Orsha','pending','full-time'),
VALUES ('Software Test Engineer IV','Kirlin LLC','Isulan','interview','remote'),
VALUES ('Web Designer III','Koch Group','San Miguel','pending','internship'),
VALUES ('Tax Accountant','Pacocha and Sons','An Lão','interview','part-time'),
VALUES ('Electrical Engineer','Weber, Glover and Quitzon','København','declined','internship'),
VALUES ('Marketing Assistant','Veum-Kulas','Guohe','pending','internship'),
VALUES ('Human Resources Manager','Luettgen, Swaniawski and Altenwerth','Fengmen','interview','part-time'),
VALUES ('Physical Therapy Assistant','Jaskolski LLC','Paoua','interview','part-time'),
VALUES ('Dental Hygienist','Bins-Ullrich','Methven','interview','internship'),
VALUES ('Cost Accountant','Price Inc','Severnyy','interview','remote'),
VALUES ('Research Nurse','Windler-Turner','Tilburg','interview','part-time'),
VALUES ('Tax Accountant','Runte-O'Reilly','Chok Chai','interview','part-time'),
VALUES ('Sales Associate','Kunde and Sons','La Mesa','declined','internship'),
VALUES ('Community Outreach Specialist','Borer, Dibbert and Larson','Svislach','interview','remote'),
VALUES ('Biostatistician IV','Heathcote, Herzog and Konopelski','Dingzhai','interview','full-time'),
VALUES ('Nuclear Power Engineer','Satterfield Group','Si Bun Rueang','pending','remote'),
VALUES ('Software Consultant','Toy Group','Belfast','interview','full-time'),
VALUES ('Programmer Analyst I','Schumm-Cormier','New Agutaya','pending','remote'),
VALUES ('Account Representative II','Labadie LLC','Paripiranga','pending','remote'),
VALUES ('Staff Accountant II','Strosin and Sons','Gnosjö','interview','remote'),
VALUES ('Web Designer IV','Swaniawski-Murphy','Liutan','interview','remote'),
VALUES ('Automation Specialist I','Kuhlman, Balistreri and Romaguera','Utmānzai','declined','remote'),
VALUES ('Civil Engineer','Erdman and Sons','Arrah','pending','remote'),
VALUES ('Payment Adjustment Coordinator','Senger-Greenfelder','Verkhozim','declined','internship'),
VALUES ('Chief Design Engineer','Rutherford-Brown','Fulong','declined','remote'),
VALUES ('Engineer IV','Cartwright LLC','Pétionville','declined','internship'),
VALUES ('Research Assistant IV','Turcotte and Sons','Būrabay','pending','full-time'),
VALUES ('Programmer I','Raynor, Harber and Boyer','Cartagena','declined','remote'),
VALUES ('Programmer II','Rohan-Feil','Lidköping','pending','full-time'),
VALUES ('Developer IV','Kirlin LLC','Zheyuan','declined','internship'),
VALUES ('Product Engineer','Hahn, Sanford and Goodwin','Liushutun','interview','internship'),
VALUES ('Safety Technician III','Gottlieb LLC','Jingmen','pending','part-time'),
VALUES ('Data Coordiator','Weissnat LLC','Néa Kíos','declined','part-time'),
VALUES ('Staff Scientist','Schneider and Sons','Wadusari','declined','full-time'),
VALUES ('Senior Sales Associate','Orn Inc','Dmitriyevka','declined','full-time'),
VALUES ('Information Systems Manager','Mraz, Weimann and Parisian','Tshela','declined','full-time'),
VALUES ('Project Manager','Cremin, Durganand Schmitt','Weton','pending','internship'),
VALUES ('Human Resources','Batz, Bruen and Miller','Pandangan Kulon','interview','remote'),
VALUES ('Administrative Officer','Denesik Group','Pergamos','interview','part-time'),
VALUES ('VP Sales','Jaskolski-Senger','Svyetlahorsk','pending','remote'),
VALUES ('Software Test Engineer III','Kihn-Roberts','Karangtengah','pending','full-time');



